services:
  c2-server:
    build:
      context: .
      dockerfile: c2.Dockerfile
    ports:
      - "8888:8888"
    stdin_open: true # Keep stdin open for interactive commands
    tty: true        # Allocate a pseudo-TTY
    networks:
      - c2_network

  exfil-server:
    build:
      context: .
      dockerfile: exfil.Dockerfile
    ports:
      - "8889:8889"
    networks:
      - c2_network

networks:
  c2_network:
    driver: bridge
